// <auto-generated />
using System;
using ExamCSharp.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamCSharp.Migrations
{
    [DbContext(typeof(HomeContext))]
    [Migration("20200124155749_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExamCSharp.Models.Funthing", b =>
                {
                    b.Property<int>("FunthingId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatorUserId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("FunthingDate");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAT");

                    b.HasKey("FunthingId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("Funthings");
                });

            modelBuilder.Entity("ExamCSharp.Models.Response", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FunthingId");

                    b.Property<int>("UserId");

                    b.HasKey("ResponseId");

                    b.HasIndex("FunthingId");

                    b.HasIndex("UserId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("ExamCSharp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExamCSharp.Models.Funthing", b =>
                {
                    b.HasOne("ExamCSharp.Models.User", "Creator")
                        .WithMany("PlannedFunthings")
                        .HasForeignKey("CreatorUserId");
                });

            modelBuilder.Entity("ExamCSharp.Models.Response", b =>
                {
                    b.HasOne("ExamCSharp.Models.Funthing", "Participating")
                        .WithMany("Participants")
                        .HasForeignKey("FunthingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ExamCSharp.Models.User", "Participant")
                        .WithMany("FunthingsAttending")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
